### PR TITLE
Update for WP 6.6

### LINKED ISSUE #157: WordPress 6.6 and JSX runtime in build scripts
Testing with WordPress 6.6 **before** updating the build process to use the new JSX runtime resulted in the following JavaScript warnings. I did not find any errors that broke functionality.

I will follow up with any issue I encounter **after** updating to use the JSX runtime.

More on the runtime change: https://make.wordpress.org/core/2024/06/06/jsx-in-wordpress-6-6/

### We'll have to search for these:

> `wp.data.select( 'core/editor' ).getSelectedBlock` is deprecated since version 5.3 and will be removed in version 6.2. Please use `wp.data.select( 'core/block-editor' ).getSelectedBlock` instead.

> wp.editor.RichTextToolbarButton is deprecated since version 5.3 and will be removed in version 6.2. Please use wp.blockEditor.RichTextToolbarButton instead.

> wp.blockEditor.RichText onSplit prop is deprecated since version 6.4. Please use block.json support key: "splitting" instead.

### Network Link
```
Warning: React does not recognize the `setAttributes` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `setattributes` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
button
Role@http://dev.local/wp-includes/js/dist/components.js?ver=54eab95952fe254d64e9:2877:38
UnforwardedTooltip@http://dev.local/wp-includes/js/dist/components.js?ver=54eab95952fe254d64e9:10210:7
UnforwardedButton@http://dev.local/wp-includes/js/dist/components.js?ver=54eab95952fe254d64e9:31665:32
li
edit@http://dev.local/wp-content/plugins/cata-blocks/blocks/network-link/build/index.js?ver=d945a8d528932060379e:1:30063
Edit@http://dev.local/wp-includes/js/dist/block-editor.js?ver=08c7639fec797fe5afb1:39005:7
```

### Shopify
```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `edit`. See https://reactjs.org/link/warning-keys for more information.
option
edit@http://dev.local/wp-content/plugins/cata-blocks/blocks/shopify/build/index.js?ver=fb0582c980e27e6a9408:1:2143
Edit@http://dev.local/wp-includes/js/dist/block-editor.js?ver=08c7639fec797fe5afb1:39005:7
```

### PR DESCRIPTION
**Pull request by douglas-johnson**
### Related Issues
- Resolves #157 

#### Source Changes
- Updated dependencies to use the tag `wp-6.6` instead of semver so we know the build is compatible with our target version of WordPress.
- Updated kicker block to use `supports.splitting` rather than an onSplit callback function.
- Updated multiple blocks because `useSetting` was deprecated in favor or `useSettings` and we use the setting `spacing.units` in multiple places.
- Updated Shopify store SelectControl to solve warning about `key` prop.
- Removed extraneous `Button` from network link block.
- Removed extra spaces from overhang format file.

#### Build Changes
- Built everything with the updated build scripts.

### Open Questions
- We lost the ability to show the social link Substack icon in the editor content. It works in the rendered content and you can see it in the side panel, but it looks to me like the available icons have been restricted to a specific set provided by WP core. This `getIconBySite` function looks at an imported list rather than finding all variations: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/social-link/social-list.js#L19

### How to Test
- [ ] All blocks work in a local WP 6.6 environment.

### CODE REVIEW

**Review by jessica-townsend — CHANGES_REQUESTED** [review]
@douglas-johnson I ran into an error when trying to add a reel clip block locally on 6.6. All other blocks worked fine
Screenshot 2024-07-10 at 11 51 30 AM

**Comment by douglas-johnson** [comment]
@jessica-townsend Does that improve if you build reel-clip? I think I fixed a typo in the source but forgot to rebuild.

**Comment by jessica-townsend** [comment]
Yes @douglas-johnson it just needs rebuilt, that fixed the issue on my end

**Review by jessica-townsend — APPROVED** [review]
Works for me now!

**Comment by douglas-johnson** [comment]
@jessica-townsend I just rebased this to include the SVG background block the recent changes to the Reel block for autosliding. Would you please re-review just those two?

**Comment by jessica-townsend** [comment]
@douglas-johnson I checked the reel block and globe background block locally on this new version and both look good to me

**Pull request merged**
